version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: salavat-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import

volumes:
  neo4j_data:
  neo4j_plugins:
  neo4j_logs:
  neo4j_import: